// @generated AUTO GENERATED - DO NOT EDIT!
// Copyright (c) 2017 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package generation

import (
	"code.uber.internal/infra/peloton/mimir-lib/model/labels"
	"code.uber.internal/infra/peloton/mimir-lib/model/metrics"
	"code.uber.internal/infra/peloton/mimir-lib/model/placement"
	"fmt"
	"math/rand"
	"time"
)

// GroupBuilder is used to generate new groups for use in tests and benchmarks.
type GroupBuilder interface {
	// Name will use the Label.String() method value of the generated value from the label template.
	Name(template labels.LabelTemplate) GroupBuilder

	// AddMetric will add a metric of the given type with the given distribution.
	AddMetric(metricType metrics.MetricType, value Distribution) GroupBuilder

	// AddLabel will add a label generated by the label template.
	AddLabel(template labels.LabelTemplate) GroupBuilder

	// Generate will generate a group that depends on the random source and the time.
	Generate(random *rand.Rand, time time.Time) *placement.Group
}

// NewGroupBuilder will create a new group builder for generating groups.
func NewGroupBuilder() GroupBuilder {
	return &groupBuilder{
		name:    labels.NewLabelTemplate(),
		metrics: map[metrics.MetricType]Distribution{},
		labels:  map[labels.LabelTemplate]struct{}{},
	}
}

type groupBuilder struct {
	name    labels.LabelTemplate
	metrics map[metrics.MetricType]Distribution
	labels  map[labels.LabelTemplate]struct{}
}

func (builder *groupBuilder) Name(template labels.LabelTemplate) GroupBuilder {
	builder.name = template
	return builder
}

func (builder *groupBuilder) AddMetric(metricType metrics.MetricType, value Distribution) GroupBuilder {
	builder.metrics[metricType] = value
	return builder
}

func (builder *groupBuilder) AddLabel(template labels.LabelTemplate) GroupBuilder {
	builder.labels[template] = struct{}{}
	return builder
}

func (builder *groupBuilder) Generate(random *rand.Rand, time time.Time) *placement.Group {
	result := placement.NewGroup(builder.name.Instantiate().String())
	for metricType, distribution := range builder.metrics {
		result.Metrics.Set(metricType, distribution.Value(random, time))
	}
	for factory := range builder.labels {
		result.Labels.Add(factory.Instantiate())
	}
	return result
}

// CreateHostGroupsBuilder will create a builder to generate groups representing hosts that belong to a rack in a
// datacenter.
func CreateHostGroupsBuilder() (builder GroupBuilder, templates labels.TemplateSet) {
	builder = NewGroupBuilder()
	templates = labels.NewTemplateSet()
	nameTemplate := labels.NewLabelTemplate(fmt.Sprintf("schemadock%v-%v",
		HostID.Variable(), Datacenter.Variable()))
	templates.Add(nameTemplate)
	rackTemplate := labels.NewLabelTemplate(Rack.Name(), Rack.Variable())
	templates.Add(rackTemplate)
	datacenterTemplate := labels.NewLabelTemplate(Datacenter.Name(), Datacenter.Variable())
	templates.Add(datacenterTemplate)
	volumeTemplate := labels.NewLabelTemplate(VolumeType.Name(), "local")
	memoryDistribution := NewDiscrete(map[float64]float64{128 * metrics.GiB: 1, 256 * metrics.GiB: 5})
	builder.Name(nameTemplate).
		AddLabel(rackTemplate).
		AddLabel(datacenterTemplate).
		AddLabel(volumeTemplate).
		AddMetric(metrics.DiskTotal, NewUniformDiscrete(6*metrics.TiB)).
		AddMetric(metrics.MemoryTotal, memoryDistribution)
	return
}

// CreateHostGroups will create a given number of groups representing hosts distributed over a given number of racks
// and all belonging to the same datacenter.
func CreateHostGroups(random *rand.Rand, builder GroupBuilder, templates labels.TemplateSet, deriver metrics.Deriver,
	racks, hosts int) []*placement.Group {
	groups := []*placement.Group{}
	for i := 0; i < hosts; i++ {
		datacenter := templates.Mappings()[Datacenter.Name()]
		templates.Bind(Rack.Name(), fmt.Sprintf("%v-a%v", datacenter, i%racks))
		templates.Bind(HostID.Name(), fmt.Sprintf("%v", i))
		group := builder.Generate(random, time.Now())
		deriver.Derive(group.Metrics)
		groups = append(groups, group)
	}
	return groups
}
