// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peloton/api/v1alpha/query/query.proto

package query

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderBy_Order int32

const (
	OrderBy_ORDER_BY_INVALID OrderBy_Order = 0
	OrderBy_ORDER_BY_ASC     OrderBy_Order = 1
	OrderBy_ORDER_BY_DESC    OrderBy_Order = 2
)

var OrderBy_Order_name = map[int32]string{
	0: "ORDER_BY_INVALID",
	1: "ORDER_BY_ASC",
	2: "ORDER_BY_DESC",
}

var OrderBy_Order_value = map[string]int32{
	"ORDER_BY_INVALID": 0,
	"ORDER_BY_ASC":     1,
	"ORDER_BY_DESC":    2,
}

func (x OrderBy_Order) String() string {
	return proto.EnumName(OrderBy_Order_name, int32(x))
}

func (OrderBy_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c1a5716dfc582a8d, []int{1, 0}
}

// A dot separated path to a object property such as config.name or
// runtime.creationTime for a job object.
type PropertyPath struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertyPath) Reset()         { *m = PropertyPath{} }
func (m *PropertyPath) String() string { return proto.CompactTextString(m) }
func (*PropertyPath) ProtoMessage()    {}
func (*PropertyPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a5716dfc582a8d, []int{0}
}

func (m *PropertyPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyPath.Unmarshal(m, b)
}
func (m *PropertyPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyPath.Marshal(b, m, deterministic)
}
func (m *PropertyPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyPath.Merge(m, src)
}
func (m *PropertyPath) XXX_Size() int {
	return xxx_messageInfo_PropertyPath.Size(m)
}
func (m *PropertyPath) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyPath.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyPath proto.InternalMessageInfo

func (m *PropertyPath) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Order by clause of a query
type OrderBy struct {
	Order                OrderBy_Order `protobuf:"varint,1,opt,name=order,proto3,enum=peloton.api.v1alpha.query.OrderBy_Order" json:"order,omitempty"`
	Property             *PropertyPath `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrderBy) Reset()         { *m = OrderBy{} }
func (m *OrderBy) String() string { return proto.CompactTextString(m) }
func (*OrderBy) ProtoMessage()    {}
func (*OrderBy) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a5716dfc582a8d, []int{1}
}

func (m *OrderBy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBy.Unmarshal(m, b)
}
func (m *OrderBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBy.Marshal(b, m, deterministic)
}
func (m *OrderBy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBy.Merge(m, src)
}
func (m *OrderBy) XXX_Size() int {
	return xxx_messageInfo_OrderBy.Size(m)
}
func (m *OrderBy) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBy.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBy proto.InternalMessageInfo

func (m *OrderBy) GetOrder() OrderBy_Order {
	if m != nil {
		return m.Order
	}
	return OrderBy_ORDER_BY_INVALID
}

func (m *OrderBy) GetProperty() *PropertyPath {
	if m != nil {
		return m.Property
	}
	return nil
}

// Pagination query spec used as argument to queries that returns a Pagination result.
type PaginationSpec struct {
	// Offset of the query for pagination
	Offset uint32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Limit per page of the query for pagination
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// List of fields to be order by in sequence
	OrderBy []*OrderBy `protobuf:"bytes,3,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Max limit of the pagination result.
	MaxLimit             uint32   `protobuf:"varint,4,opt,name=max_limit,json=maxLimit,proto3" json:"max_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationSpec) Reset()         { *m = PaginationSpec{} }
func (m *PaginationSpec) String() string { return proto.CompactTextString(m) }
func (*PaginationSpec) ProtoMessage()    {}
func (*PaginationSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a5716dfc582a8d, []int{2}
}

func (m *PaginationSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationSpec.Unmarshal(m, b)
}
func (m *PaginationSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationSpec.Marshal(b, m, deterministic)
}
func (m *PaginationSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationSpec.Merge(m, src)
}
func (m *PaginationSpec) XXX_Size() int {
	return xxx_messageInfo_PaginationSpec.Size(m)
}
func (m *PaginationSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationSpec proto.InternalMessageInfo

func (m *PaginationSpec) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PaginationSpec) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PaginationSpec) GetOrderBy() []*OrderBy {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *PaginationSpec) GetMaxLimit() uint32 {
	if m != nil {
		return m.MaxLimit
	}
	return 0
}

// Generic pagination for a list of records to be returned by a query
type Pagination struct {
	// Offset of the pagination for a query result
	Offset uint32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Limit of the pagination for a query result
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Total number of records for a query result
	Total                uint32   `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a5716dfc582a8d, []int{3}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Pagination) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterEnum("peloton.api.v1alpha.query.OrderBy_Order", OrderBy_Order_name, OrderBy_Order_value)
	proto.RegisterType((*PropertyPath)(nil), "peloton.api.v1alpha.query.PropertyPath")
	proto.RegisterType((*OrderBy)(nil), "peloton.api.v1alpha.query.OrderBy")
	proto.RegisterType((*PaginationSpec)(nil), "peloton.api.v1alpha.query.PaginationSpec")
	proto.RegisterType((*Pagination)(nil), "peloton.api.v1alpha.query.Pagination")
}

func init() {
	proto.RegisterFile("peloton/api/v1alpha/query/query.proto", fileDescriptor_c1a5716dfc582a8d)
}

var fileDescriptor_c1a5716dfc582a8d = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0xb5, 0x9b, 0xdd, 0xc7, 0xdd, 0x07, 0x35, 0x0c, 0xe9, 0xf0, 0x65, 0x14, 0xc5, 0x3e, 0x75,
	0x38, 0xc1, 0x37, 0x85, 0x75, 0xdb, 0xc3, 0x60, 0xb8, 0x92, 0x81, 0xa0, 0x2f, 0x25, 0xd3, 0xcc,
	0x15, 0xba, 0x25, 0xc6, 0x6c, 0xac, 0x7f, 0xc5, 0x9f, 0xe5, 0x2f, 0x92, 0x25, 0x61, 0xfa, 0x52,
	0xc5, 0x97, 0x24, 0xe7, 0x72, 0xee, 0xc9, 0xb9, 0x97, 0x03, 0x17, 0x9c, 0xa6, 0x4c, 0xb2, 0x75,
	0x97, 0xf0, 0xa4, 0xbb, 0xbd, 0x22, 0x29, 0x5f, 0x92, 0xee, 0xdb, 0x86, 0x8a, 0x4c, 0x9f, 0x01,
	0x17, 0x4c, 0x32, 0xd4, 0x36, 0xb4, 0x80, 0xf0, 0x24, 0x30, 0xb4, 0x40, 0x11, 0xbc, 0x73, 0xa8,
	0x47, 0x82, 0x71, 0x2a, 0x64, 0x16, 0x11, 0xb9, 0x44, 0x2d, 0xb0, 0xb7, 0x24, 0xdd, 0x50, 0xd7,
	0xea, 0x58, 0x7e, 0x15, 0x6b, 0xe0, 0x7d, 0x5a, 0x50, 0x9e, 0x8a, 0x17, 0x2a, 0xc2, 0x0c, 0xdd,
	0x81, 0xcd, 0xf6, 0x4f, 0xc5, 0x68, 0xf6, 0xfc, 0x20, 0x57, 0x3c, 0x30, 0x2d, 0xfa, 0xc6, 0xba,
	0x0d, 0x0d, 0xa0, 0xc2, 0xcd, 0x8f, 0x6e, 0xa1, 0x63, 0xf9, 0xb5, 0xde, 0xe5, 0x2f, 0x12, 0x3f,
	0xcd, 0xe1, 0x43, 0xa3, 0x17, 0x82, 0xad, 0x44, 0x51, 0x0b, 0x9c, 0x29, 0x1e, 0x8e, 0x70, 0x1c,
	0x3e, 0xc6, 0xe3, 0xfb, 0x87, 0xfe, 0x64, 0x3c, 0x74, 0x8e, 0x90, 0x03, 0xf5, 0x43, 0xb5, 0x3f,
	0x1b, 0x38, 0x16, 0x3a, 0x81, 0xc6, 0xa1, 0x32, 0x1c, 0xcd, 0x06, 0x4e, 0xc1, 0xfb, 0xb0, 0xa0,
	0x19, 0x91, 0xd7, 0x64, 0x4d, 0x64, 0xc2, 0xd6, 0x33, 0x4e, 0x9f, 0xd1, 0x29, 0x94, 0xd8, 0x62,
	0xf1, 0x4e, 0xa5, 0x1a, 0xae, 0x81, 0x0d, 0xda, 0x6f, 0x25, 0x4d, 0x56, 0x89, 0x54, 0x86, 0x1b,
	0x58, 0x03, 0x74, 0x0b, 0x15, 0x35, 0x52, 0x3c, 0xcf, 0xdc, 0x62, 0xa7, 0xe8, 0xd7, 0x7a, 0xde,
	0xdf, 0xcb, 0xc0, 0x65, 0x66, 0x16, 0x79, 0x06, 0xd5, 0x15, 0xd9, 0xc5, 0x5a, 0xf8, 0x58, 0x09,
	0x57, 0x56, 0x64, 0x37, 0xd9, 0x63, 0x2f, 0x02, 0xf8, 0xf6, 0xf6, 0x4f, 0x5f, 0x2d, 0xb0, 0x25,
	0x93, 0x24, 0x75, 0x8b, 0xba, 0xaa, 0x40, 0x78, 0x03, 0xf9, 0x31, 0x78, 0x6a, 0xe7, 0x06, 0x69,
	0x5e, 0x52, 0x19, 0xba, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x7a, 0x77, 0x70, 0x6c, 0x02,
	0x00, 0x00,
}
