#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,slots,utf8strings
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

AURORA_EXECUTOR_NAME = "AuroraExecutor"
ACTIVE_STATES = set([
    9,
    17,
    6,
    0,
    13,
    12,
    2,
    1,
    16,
])
SLAVE_ASSIGNED_STATES = set([
    9,
    17,
    6,
    13,
    12,
    2,
    1,
])
LIVE_STATES = set([
    6,
    13,
    12,
    17,
    2,
])
TERMINAL_STATES = set([
    4,
    3,
    5,
    7,
])
GOOD_IDENTIFIER_PATTERN = "^[\\w\\-\\.]+$"
GOOD_IDENTIFIER_PATTERN_JVM = "^[\\w\\-\\.]+$"
GOOD_IDENTIFIER_PATTERN_PYTHON = "^[\\w\\-\\.]+$"
ACTIVE_JOB_UPDATE_STATES = set([
    0,
    1,
    2,
    3,
    9,
    10,
])
AWAITNG_PULSE_JOB_UPDATE_STATES = set([
    9,
    10,
])
BYPASS_LEADER_REDIRECT_HEADER_NAME = "Bypass-Leader-Redirect"
TASK_FILESYSTEM_MOUNT_POINT = "taskfs"
