// Code generated by thriftrw v1.19.1. DO NOT EDIT.
// @generated

package api

import (
	errors "errors"
	fmt "fmt"
	multierr "go.uber.org/multierr"
	wire "go.uber.org/thriftrw/wire"
	zapcore "go.uber.org/zap/zapcore"
	strings "strings"
)

// AuroraSchedulerManager_StartJobUpdate_Args represents the arguments for the AuroraSchedulerManager.startJobUpdate function.
//
// The arguments for startJobUpdate are sent and received over the wire as this struct.
type AuroraSchedulerManager_StartJobUpdate_Args struct {
	// A description of how to change the job.
	Request *JobUpdateRequest `json:"request,omitempty"`
	// A user-specified message to include with the induced job update state change.
	Message *string `json:"message,omitempty"`
}

// ToWire translates a AuroraSchedulerManager_StartJobUpdate_Args struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *AuroraSchedulerManager_StartJobUpdate_Args) ToWire() (wire.Value, error) {
	var (
		fields [2]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Request != nil {
		w, err = v.Request.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	if v.Message != nil {
		w, err = wire.NewValueString(*(v.Message)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 3, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _JobUpdateRequest_Read(w wire.Value) (*JobUpdateRequest, error) {
	var v JobUpdateRequest
	err := v.FromWire(w)
	return &v, err
}

// FromWire deserializes a AuroraSchedulerManager_StartJobUpdate_Args struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a AuroraSchedulerManager_StartJobUpdate_Args struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v AuroraSchedulerManager_StartJobUpdate_Args
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *AuroraSchedulerManager_StartJobUpdate_Args) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.Request, err = _JobUpdateRequest_Read(field.Value)
				if err != nil {
					return err
				}

			}
		case 3:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.Message = &x
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a AuroraSchedulerManager_StartJobUpdate_Args
// struct.
func (v *AuroraSchedulerManager_StartJobUpdate_Args) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [2]string
	i := 0
	if v.Request != nil {
		fields[i] = fmt.Sprintf("Request: %v", v.Request)
		i++
	}
	if v.Message != nil {
		fields[i] = fmt.Sprintf("Message: %v", *(v.Message))
		i++
	}

	return fmt.Sprintf("AuroraSchedulerManager_StartJobUpdate_Args{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this AuroraSchedulerManager_StartJobUpdate_Args match the
// provided AuroraSchedulerManager_StartJobUpdate_Args.
//
// This function performs a deep comparison.
func (v *AuroraSchedulerManager_StartJobUpdate_Args) Equals(rhs *AuroraSchedulerManager_StartJobUpdate_Args) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !((v.Request == nil && rhs.Request == nil) || (v.Request != nil && rhs.Request != nil && v.Request.Equals(rhs.Request))) {
		return false
	}
	if !_String_EqualsPtr(v.Message, rhs.Message) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of AuroraSchedulerManager_StartJobUpdate_Args.
func (v *AuroraSchedulerManager_StartJobUpdate_Args) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Request != nil {
		err = multierr.Append(err, enc.AddObject("request", v.Request))
	}
	if v.Message != nil {
		enc.AddString("message", *v.Message)
	}
	return err
}

// GetRequest returns the value of Request if it is set or its
// zero value if it is unset.
func (v *AuroraSchedulerManager_StartJobUpdate_Args) GetRequest() (o *JobUpdateRequest) {
	if v != nil && v.Request != nil {
		return v.Request
	}

	return
}

// IsSetRequest returns true if Request is not nil.
func (v *AuroraSchedulerManager_StartJobUpdate_Args) IsSetRequest() bool {
	return v != nil && v.Request != nil
}

// GetMessage returns the value of Message if it is set or its
// zero value if it is unset.
func (v *AuroraSchedulerManager_StartJobUpdate_Args) GetMessage() (o string) {
	if v != nil && v.Message != nil {
		return *v.Message
	}

	return
}

// IsSetMessage returns true if Message is not nil.
func (v *AuroraSchedulerManager_StartJobUpdate_Args) IsSetMessage() bool {
	return v != nil && v.Message != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the arguments.
//
// This will always be "startJobUpdate" for this struct.
func (v *AuroraSchedulerManager_StartJobUpdate_Args) MethodName() string {
	return "startJobUpdate"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Call for this struct.
func (v *AuroraSchedulerManager_StartJobUpdate_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

// AuroraSchedulerManager_StartJobUpdate_Helper provides functions that aid in handling the
// parameters and return values of the AuroraSchedulerManager.startJobUpdate
// function.
var AuroraSchedulerManager_StartJobUpdate_Helper = struct {
	// Args accepts the parameters of startJobUpdate in-order and returns
	// the arguments struct for the function.
	Args func(
		request *JobUpdateRequest,
		message *string,
	) *AuroraSchedulerManager_StartJobUpdate_Args

	// IsException returns true if the given error can be thrown
	// by startJobUpdate.
	//
	// An error can be thrown by startJobUpdate only if the
	// corresponding exception type was mentioned in the 'throws'
	// section for it in the Thrift file.
	IsException func(error) bool

	// WrapResponse returns the result struct for startJobUpdate
	// given its return value and error.
	//
	// This allows mapping values and errors returned by
	// startJobUpdate into a serializable result struct.
	// WrapResponse returns a non-nil error if the provided
	// error cannot be thrown by startJobUpdate
	//
	//   value, err := startJobUpdate(args)
	//   result, err := AuroraSchedulerManager_StartJobUpdate_Helper.WrapResponse(value, err)
	//   if err != nil {
	//     return fmt.Errorf("unexpected error from startJobUpdate: %v", err)
	//   }
	//   serialize(result)
	WrapResponse func(*Response, error) (*AuroraSchedulerManager_StartJobUpdate_Result, error)

	// UnwrapResponse takes the result struct for startJobUpdate
	// and returns the value or error returned by it.
	//
	// The error is non-nil only if startJobUpdate threw an
	// exception.
	//
	//   result := deserialize(bytes)
	//   value, err := AuroraSchedulerManager_StartJobUpdate_Helper.UnwrapResponse(result)
	UnwrapResponse func(*AuroraSchedulerManager_StartJobUpdate_Result) (*Response, error)
}{}

func init() {
	AuroraSchedulerManager_StartJobUpdate_Helper.Args = func(
		request *JobUpdateRequest,
		message *string,
	) *AuroraSchedulerManager_StartJobUpdate_Args {
		return &AuroraSchedulerManager_StartJobUpdate_Args{
			Request: request,
			Message: message,
		}
	}

	AuroraSchedulerManager_StartJobUpdate_Helper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}

	AuroraSchedulerManager_StartJobUpdate_Helper.WrapResponse = func(success *Response, err error) (*AuroraSchedulerManager_StartJobUpdate_Result, error) {
		if err == nil {
			return &AuroraSchedulerManager_StartJobUpdate_Result{Success: success}, nil
		}

		return nil, err
	}
	AuroraSchedulerManager_StartJobUpdate_Helper.UnwrapResponse = func(result *AuroraSchedulerManager_StartJobUpdate_Result) (success *Response, err error) {

		if result.Success != nil {
			success = result.Success
			return
		}

		err = errors.New("expected a non-void result")
		return
	}

}

// AuroraSchedulerManager_StartJobUpdate_Result represents the result of a AuroraSchedulerManager.startJobUpdate function call.
//
// The result of a startJobUpdate execution is sent and received over the wire as this struct.
//
// Success is set only if the function did not throw an exception.
type AuroraSchedulerManager_StartJobUpdate_Result struct {
	// Value returned by startJobUpdate after a successful execution.
	Success *Response `json:"success,omitempty"`
}

// ToWire translates a AuroraSchedulerManager_StartJobUpdate_Result struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *AuroraSchedulerManager_StartJobUpdate_Result) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}

	if i != 1 {
		return wire.Value{}, fmt.Errorf("AuroraSchedulerManager_StartJobUpdate_Result should have exactly one field: got %v fields", i)
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a AuroraSchedulerManager_StartJobUpdate_Result struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a AuroraSchedulerManager_StartJobUpdate_Result struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v AuroraSchedulerManager_StartJobUpdate_Result
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *AuroraSchedulerManager_StartJobUpdate_Result) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _Response_Read(field.Value)
				if err != nil {
					return err
				}

			}
		}
	}

	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("AuroraSchedulerManager_StartJobUpdate_Result should have exactly one field: got %v fields", count)
	}

	return nil
}

// String returns a readable string representation of a AuroraSchedulerManager_StartJobUpdate_Result
// struct.
func (v *AuroraSchedulerManager_StartJobUpdate_Result) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}

	return fmt.Sprintf("AuroraSchedulerManager_StartJobUpdate_Result{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this AuroraSchedulerManager_StartJobUpdate_Result match the
// provided AuroraSchedulerManager_StartJobUpdate_Result.
//
// This function performs a deep comparison.
func (v *AuroraSchedulerManager_StartJobUpdate_Result) Equals(rhs *AuroraSchedulerManager_StartJobUpdate_Result) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !((v.Success == nil && rhs.Success == nil) || (v.Success != nil && rhs.Success != nil && v.Success.Equals(rhs.Success))) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of AuroraSchedulerManager_StartJobUpdate_Result.
func (v *AuroraSchedulerManager_StartJobUpdate_Result) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Success != nil {
		err = multierr.Append(err, enc.AddObject("success", v.Success))
	}
	return err
}

// GetSuccess returns the value of Success if it is set or its
// zero value if it is unset.
func (v *AuroraSchedulerManager_StartJobUpdate_Result) GetSuccess() (o *Response) {
	if v != nil && v.Success != nil {
		return v.Success
	}

	return
}

// IsSetSuccess returns true if Success is not nil.
func (v *AuroraSchedulerManager_StartJobUpdate_Result) IsSetSuccess() bool {
	return v != nil && v.Success != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the result.
//
// This will always be "startJobUpdate" for this struct.
func (v *AuroraSchedulerManager_StartJobUpdate_Result) MethodName() string {
	return "startJobUpdate"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Reply for this struct.
func (v *AuroraSchedulerManager_StartJobUpdate_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
