// Code generated by thriftrw v1.19.1. DO NOT EDIT.
// @generated

package api

import (
	errors "errors"
	fmt "fmt"
	multierr "go.uber.org/multierr"
	wire "go.uber.org/thriftrw/wire"
	zapcore "go.uber.org/zap/zapcore"
	strings "strings"
)

// AuroraSchedulerManager_AddInstances_Args represents the arguments for the AuroraSchedulerManager.addInstances function.
//
// The arguments for addInstances are sent and received over the wire as this struct.
type AuroraSchedulerManager_AddInstances_Args struct {
	Key   *InstanceKey `json:"key,omitempty"`
	Count *int32       `json:"count,omitempty"`
}

// ToWire translates a AuroraSchedulerManager_AddInstances_Args struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *AuroraSchedulerManager_AddInstances_Args) ToWire() (wire.Value, error) {
	var (
		fields [2]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Key != nil {
		w, err = v.Key.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 3, Value: w}
		i++
	}
	if v.Count != nil {
		w, err = wire.NewValueI32(*(v.Count)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 4, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _InstanceKey_Read(w wire.Value) (*InstanceKey, error) {
	var v InstanceKey
	err := v.FromWire(w)
	return &v, err
}

// FromWire deserializes a AuroraSchedulerManager_AddInstances_Args struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a AuroraSchedulerManager_AddInstances_Args struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v AuroraSchedulerManager_AddInstances_Args
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *AuroraSchedulerManager_AddInstances_Args) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 3:
			if field.Value.Type() == wire.TStruct {
				v.Key, err = _InstanceKey_Read(field.Value)
				if err != nil {
					return err
				}

			}
		case 4:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.Count = &x
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a AuroraSchedulerManager_AddInstances_Args
// struct.
func (v *AuroraSchedulerManager_AddInstances_Args) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [2]string
	i := 0
	if v.Key != nil {
		fields[i] = fmt.Sprintf("Key: %v", v.Key)
		i++
	}
	if v.Count != nil {
		fields[i] = fmt.Sprintf("Count: %v", *(v.Count))
		i++
	}

	return fmt.Sprintf("AuroraSchedulerManager_AddInstances_Args{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this AuroraSchedulerManager_AddInstances_Args match the
// provided AuroraSchedulerManager_AddInstances_Args.
//
// This function performs a deep comparison.
func (v *AuroraSchedulerManager_AddInstances_Args) Equals(rhs *AuroraSchedulerManager_AddInstances_Args) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !((v.Key == nil && rhs.Key == nil) || (v.Key != nil && rhs.Key != nil && v.Key.Equals(rhs.Key))) {
		return false
	}
	if !_I32_EqualsPtr(v.Count, rhs.Count) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of AuroraSchedulerManager_AddInstances_Args.
func (v *AuroraSchedulerManager_AddInstances_Args) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Key != nil {
		err = multierr.Append(err, enc.AddObject("key", v.Key))
	}
	if v.Count != nil {
		enc.AddInt32("count", *v.Count)
	}
	return err
}

// GetKey returns the value of Key if it is set or its
// zero value if it is unset.
func (v *AuroraSchedulerManager_AddInstances_Args) GetKey() (o *InstanceKey) {
	if v != nil && v.Key != nil {
		return v.Key
	}

	return
}

// IsSetKey returns true if Key is not nil.
func (v *AuroraSchedulerManager_AddInstances_Args) IsSetKey() bool {
	return v != nil && v.Key != nil
}

// GetCount returns the value of Count if it is set or its
// zero value if it is unset.
func (v *AuroraSchedulerManager_AddInstances_Args) GetCount() (o int32) {
	if v != nil && v.Count != nil {
		return *v.Count
	}

	return
}

// IsSetCount returns true if Count is not nil.
func (v *AuroraSchedulerManager_AddInstances_Args) IsSetCount() bool {
	return v != nil && v.Count != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the arguments.
//
// This will always be "addInstances" for this struct.
func (v *AuroraSchedulerManager_AddInstances_Args) MethodName() string {
	return "addInstances"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Call for this struct.
func (v *AuroraSchedulerManager_AddInstances_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

// AuroraSchedulerManager_AddInstances_Helper provides functions that aid in handling the
// parameters and return values of the AuroraSchedulerManager.addInstances
// function.
var AuroraSchedulerManager_AddInstances_Helper = struct {
	// Args accepts the parameters of addInstances in-order and returns
	// the arguments struct for the function.
	Args func(
		key *InstanceKey,
		count *int32,
	) *AuroraSchedulerManager_AddInstances_Args

	// IsException returns true if the given error can be thrown
	// by addInstances.
	//
	// An error can be thrown by addInstances only if the
	// corresponding exception type was mentioned in the 'throws'
	// section for it in the Thrift file.
	IsException func(error) bool

	// WrapResponse returns the result struct for addInstances
	// given its return value and error.
	//
	// This allows mapping values and errors returned by
	// addInstances into a serializable result struct.
	// WrapResponse returns a non-nil error if the provided
	// error cannot be thrown by addInstances
	//
	//   value, err := addInstances(args)
	//   result, err := AuroraSchedulerManager_AddInstances_Helper.WrapResponse(value, err)
	//   if err != nil {
	//     return fmt.Errorf("unexpected error from addInstances: %v", err)
	//   }
	//   serialize(result)
	WrapResponse func(*Response, error) (*AuroraSchedulerManager_AddInstances_Result, error)

	// UnwrapResponse takes the result struct for addInstances
	// and returns the value or error returned by it.
	//
	// The error is non-nil only if addInstances threw an
	// exception.
	//
	//   result := deserialize(bytes)
	//   value, err := AuroraSchedulerManager_AddInstances_Helper.UnwrapResponse(result)
	UnwrapResponse func(*AuroraSchedulerManager_AddInstances_Result) (*Response, error)
}{}

func init() {
	AuroraSchedulerManager_AddInstances_Helper.Args = func(
		key *InstanceKey,
		count *int32,
	) *AuroraSchedulerManager_AddInstances_Args {
		return &AuroraSchedulerManager_AddInstances_Args{
			Key:   key,
			Count: count,
		}
	}

	AuroraSchedulerManager_AddInstances_Helper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}

	AuroraSchedulerManager_AddInstances_Helper.WrapResponse = func(success *Response, err error) (*AuroraSchedulerManager_AddInstances_Result, error) {
		if err == nil {
			return &AuroraSchedulerManager_AddInstances_Result{Success: success}, nil
		}

		return nil, err
	}
	AuroraSchedulerManager_AddInstances_Helper.UnwrapResponse = func(result *AuroraSchedulerManager_AddInstances_Result) (success *Response, err error) {

		if result.Success != nil {
			success = result.Success
			return
		}

		err = errors.New("expected a non-void result")
		return
	}

}

// AuroraSchedulerManager_AddInstances_Result represents the result of a AuroraSchedulerManager.addInstances function call.
//
// The result of a addInstances execution is sent and received over the wire as this struct.
//
// Success is set only if the function did not throw an exception.
type AuroraSchedulerManager_AddInstances_Result struct {
	// Value returned by addInstances after a successful execution.
	Success *Response `json:"success,omitempty"`
}

// ToWire translates a AuroraSchedulerManager_AddInstances_Result struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *AuroraSchedulerManager_AddInstances_Result) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}

	if i != 1 {
		return wire.Value{}, fmt.Errorf("AuroraSchedulerManager_AddInstances_Result should have exactly one field: got %v fields", i)
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a AuroraSchedulerManager_AddInstances_Result struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a AuroraSchedulerManager_AddInstances_Result struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v AuroraSchedulerManager_AddInstances_Result
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *AuroraSchedulerManager_AddInstances_Result) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _Response_Read(field.Value)
				if err != nil {
					return err
				}

			}
		}
	}

	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("AuroraSchedulerManager_AddInstances_Result should have exactly one field: got %v fields", count)
	}

	return nil
}

// String returns a readable string representation of a AuroraSchedulerManager_AddInstances_Result
// struct.
func (v *AuroraSchedulerManager_AddInstances_Result) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}

	return fmt.Sprintf("AuroraSchedulerManager_AddInstances_Result{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this AuroraSchedulerManager_AddInstances_Result match the
// provided AuroraSchedulerManager_AddInstances_Result.
//
// This function performs a deep comparison.
func (v *AuroraSchedulerManager_AddInstances_Result) Equals(rhs *AuroraSchedulerManager_AddInstances_Result) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !((v.Success == nil && rhs.Success == nil) || (v.Success != nil && rhs.Success != nil && v.Success.Equals(rhs.Success))) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of AuroraSchedulerManager_AddInstances_Result.
func (v *AuroraSchedulerManager_AddInstances_Result) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Success != nil {
		err = multierr.Append(err, enc.AddObject("success", v.Success))
	}
	return err
}

// GetSuccess returns the value of Success if it is set or its
// zero value if it is unset.
func (v *AuroraSchedulerManager_AddInstances_Result) GetSuccess() (o *Response) {
	if v != nil && v.Success != nil {
		return v.Success
	}

	return
}

// IsSetSuccess returns true if Success is not nil.
func (v *AuroraSchedulerManager_AddInstances_Result) IsSetSuccess() bool {
	return v != nil && v.Success != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the result.
//
// This will always be "addInstances" for this struct.
func (v *AuroraSchedulerManager_AddInstances_Result) MethodName() string {
	return "addInstances"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Reply for this struct.
func (v *AuroraSchedulerManager_AddInstances_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
