// Code generated by thriftrw v1.19.1. DO NOT EDIT.
// @generated

package api

import (
	errors "errors"
	fmt "fmt"
	multierr "go.uber.org/multierr"
	wire "go.uber.org/thriftrw/wire"
	zapcore "go.uber.org/zap/zapcore"
	strings "strings"
)

// AuroraAdmin_ForceTaskState_Args represents the arguments for the AuroraAdmin.forceTaskState function.
//
// The arguments for forceTaskState are sent and received over the wire as this struct.
type AuroraAdmin_ForceTaskState_Args struct {
	TaskId *string         `json:"taskId,omitempty"`
	Status *ScheduleStatus `json:"status,omitempty"`
}

// ToWire translates a AuroraAdmin_ForceTaskState_Args struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *AuroraAdmin_ForceTaskState_Args) ToWire() (wire.Value, error) {
	var (
		fields [2]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.TaskId != nil {
		w, err = wire.NewValueString(*(v.TaskId)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	if v.Status != nil {
		w, err = v.Status.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 2, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a AuroraAdmin_ForceTaskState_Args struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a AuroraAdmin_ForceTaskState_Args struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v AuroraAdmin_ForceTaskState_Args
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *AuroraAdmin_ForceTaskState_Args) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.TaskId = &x
				if err != nil {
					return err
				}

			}
		case 2:
			if field.Value.Type() == wire.TI32 {
				var x ScheduleStatus
				x, err = _ScheduleStatus_Read(field.Value)
				v.Status = &x
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a AuroraAdmin_ForceTaskState_Args
// struct.
func (v *AuroraAdmin_ForceTaskState_Args) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [2]string
	i := 0
	if v.TaskId != nil {
		fields[i] = fmt.Sprintf("TaskId: %v", *(v.TaskId))
		i++
	}
	if v.Status != nil {
		fields[i] = fmt.Sprintf("Status: %v", *(v.Status))
		i++
	}

	return fmt.Sprintf("AuroraAdmin_ForceTaskState_Args{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this AuroraAdmin_ForceTaskState_Args match the
// provided AuroraAdmin_ForceTaskState_Args.
//
// This function performs a deep comparison.
func (v *AuroraAdmin_ForceTaskState_Args) Equals(rhs *AuroraAdmin_ForceTaskState_Args) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !_String_EqualsPtr(v.TaskId, rhs.TaskId) {
		return false
	}
	if !_ScheduleStatus_EqualsPtr(v.Status, rhs.Status) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of AuroraAdmin_ForceTaskState_Args.
func (v *AuroraAdmin_ForceTaskState_Args) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.TaskId != nil {
		enc.AddString("taskId", *v.TaskId)
	}
	if v.Status != nil {
		err = multierr.Append(err, enc.AddObject("status", *v.Status))
	}
	return err
}

// GetTaskId returns the value of TaskId if it is set or its
// zero value if it is unset.
func (v *AuroraAdmin_ForceTaskState_Args) GetTaskId() (o string) {
	if v != nil && v.TaskId != nil {
		return *v.TaskId
	}

	return
}

// IsSetTaskId returns true if TaskId is not nil.
func (v *AuroraAdmin_ForceTaskState_Args) IsSetTaskId() bool {
	return v != nil && v.TaskId != nil
}

// GetStatus returns the value of Status if it is set or its
// zero value if it is unset.
func (v *AuroraAdmin_ForceTaskState_Args) GetStatus() (o ScheduleStatus) {
	if v != nil && v.Status != nil {
		return *v.Status
	}

	return
}

// IsSetStatus returns true if Status is not nil.
func (v *AuroraAdmin_ForceTaskState_Args) IsSetStatus() bool {
	return v != nil && v.Status != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the arguments.
//
// This will always be "forceTaskState" for this struct.
func (v *AuroraAdmin_ForceTaskState_Args) MethodName() string {
	return "forceTaskState"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Call for this struct.
func (v *AuroraAdmin_ForceTaskState_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

// AuroraAdmin_ForceTaskState_Helper provides functions that aid in handling the
// parameters and return values of the AuroraAdmin.forceTaskState
// function.
var AuroraAdmin_ForceTaskState_Helper = struct {
	// Args accepts the parameters of forceTaskState in-order and returns
	// the arguments struct for the function.
	Args func(
		taskId *string,
		status *ScheduleStatus,
	) *AuroraAdmin_ForceTaskState_Args

	// IsException returns true if the given error can be thrown
	// by forceTaskState.
	//
	// An error can be thrown by forceTaskState only if the
	// corresponding exception type was mentioned in the 'throws'
	// section for it in the Thrift file.
	IsException func(error) bool

	// WrapResponse returns the result struct for forceTaskState
	// given its return value and error.
	//
	// This allows mapping values and errors returned by
	// forceTaskState into a serializable result struct.
	// WrapResponse returns a non-nil error if the provided
	// error cannot be thrown by forceTaskState
	//
	//   value, err := forceTaskState(args)
	//   result, err := AuroraAdmin_ForceTaskState_Helper.WrapResponse(value, err)
	//   if err != nil {
	//     return fmt.Errorf("unexpected error from forceTaskState: %v", err)
	//   }
	//   serialize(result)
	WrapResponse func(*Response, error) (*AuroraAdmin_ForceTaskState_Result, error)

	// UnwrapResponse takes the result struct for forceTaskState
	// and returns the value or error returned by it.
	//
	// The error is non-nil only if forceTaskState threw an
	// exception.
	//
	//   result := deserialize(bytes)
	//   value, err := AuroraAdmin_ForceTaskState_Helper.UnwrapResponse(result)
	UnwrapResponse func(*AuroraAdmin_ForceTaskState_Result) (*Response, error)
}{}

func init() {
	AuroraAdmin_ForceTaskState_Helper.Args = func(
		taskId *string,
		status *ScheduleStatus,
	) *AuroraAdmin_ForceTaskState_Args {
		return &AuroraAdmin_ForceTaskState_Args{
			TaskId: taskId,
			Status: status,
		}
	}

	AuroraAdmin_ForceTaskState_Helper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}

	AuroraAdmin_ForceTaskState_Helper.WrapResponse = func(success *Response, err error) (*AuroraAdmin_ForceTaskState_Result, error) {
		if err == nil {
			return &AuroraAdmin_ForceTaskState_Result{Success: success}, nil
		}

		return nil, err
	}
	AuroraAdmin_ForceTaskState_Helper.UnwrapResponse = func(result *AuroraAdmin_ForceTaskState_Result) (success *Response, err error) {

		if result.Success != nil {
			success = result.Success
			return
		}

		err = errors.New("expected a non-void result")
		return
	}

}

// AuroraAdmin_ForceTaskState_Result represents the result of a AuroraAdmin.forceTaskState function call.
//
// The result of a forceTaskState execution is sent and received over the wire as this struct.
//
// Success is set only if the function did not throw an exception.
type AuroraAdmin_ForceTaskState_Result struct {
	// Value returned by forceTaskState after a successful execution.
	Success *Response `json:"success,omitempty"`
}

// ToWire translates a AuroraAdmin_ForceTaskState_Result struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *AuroraAdmin_ForceTaskState_Result) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}

	if i != 1 {
		return wire.Value{}, fmt.Errorf("AuroraAdmin_ForceTaskState_Result should have exactly one field: got %v fields", i)
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a AuroraAdmin_ForceTaskState_Result struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a AuroraAdmin_ForceTaskState_Result struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v AuroraAdmin_ForceTaskState_Result
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *AuroraAdmin_ForceTaskState_Result) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _Response_Read(field.Value)
				if err != nil {
					return err
				}

			}
		}
	}

	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("AuroraAdmin_ForceTaskState_Result should have exactly one field: got %v fields", count)
	}

	return nil
}

// String returns a readable string representation of a AuroraAdmin_ForceTaskState_Result
// struct.
func (v *AuroraAdmin_ForceTaskState_Result) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}

	return fmt.Sprintf("AuroraAdmin_ForceTaskState_Result{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this AuroraAdmin_ForceTaskState_Result match the
// provided AuroraAdmin_ForceTaskState_Result.
//
// This function performs a deep comparison.
func (v *AuroraAdmin_ForceTaskState_Result) Equals(rhs *AuroraAdmin_ForceTaskState_Result) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !((v.Success == nil && rhs.Success == nil) || (v.Success != nil && rhs.Success != nil && v.Success.Equals(rhs.Success))) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of AuroraAdmin_ForceTaskState_Result.
func (v *AuroraAdmin_ForceTaskState_Result) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Success != nil {
		err = multierr.Append(err, enc.AddObject("success", v.Success))
	}
	return err
}

// GetSuccess returns the value of Success if it is set or its
// zero value if it is unset.
func (v *AuroraAdmin_ForceTaskState_Result) GetSuccess() (o *Response) {
	if v != nil && v.Success != nil {
		return v.Success
	}

	return
}

// IsSetSuccess returns true if Success is not nil.
func (v *AuroraAdmin_ForceTaskState_Result) IsSetSuccess() bool {
	return v != nil && v.Success != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the result.
//
// This will always be "forceTaskState" for this struct.
func (v *AuroraAdmin_ForceTaskState_Result) MethodName() string {
	return "forceTaskState"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Reply for this struct.
func (v *AuroraAdmin_ForceTaskState_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
