// Code generated by thriftrw v1.19.1. DO NOT EDIT.
// @generated

package api

import (
	errors "errors"
	fmt "fmt"
	multierr "go.uber.org/multierr"
	wire "go.uber.org/thriftrw/wire"
	zapcore "go.uber.org/zap/zapcore"
	strings "strings"
)

// ReadOnlyScheduler_GetConfigSummary_Args represents the arguments for the ReadOnlyScheduler.getConfigSummary function.
//
// The arguments for getConfigSummary are sent and received over the wire as this struct.
type ReadOnlyScheduler_GetConfigSummary_Args struct {
	Job *JobKey `json:"job,omitempty"`
}

// ToWire translates a ReadOnlyScheduler_GetConfigSummary_Args struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ReadOnlyScheduler_GetConfigSummary_Args) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Job != nil {
		w, err = v.Job.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a ReadOnlyScheduler_GetConfigSummary_Args struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ReadOnlyScheduler_GetConfigSummary_Args struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ReadOnlyScheduler_GetConfigSummary_Args
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ReadOnlyScheduler_GetConfigSummary_Args) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.Job, err = _JobKey_Read(field.Value)
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a ReadOnlyScheduler_GetConfigSummary_Args
// struct.
func (v *ReadOnlyScheduler_GetConfigSummary_Args) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [1]string
	i := 0
	if v.Job != nil {
		fields[i] = fmt.Sprintf("Job: %v", v.Job)
		i++
	}

	return fmt.Sprintf("ReadOnlyScheduler_GetConfigSummary_Args{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this ReadOnlyScheduler_GetConfigSummary_Args match the
// provided ReadOnlyScheduler_GetConfigSummary_Args.
//
// This function performs a deep comparison.
func (v *ReadOnlyScheduler_GetConfigSummary_Args) Equals(rhs *ReadOnlyScheduler_GetConfigSummary_Args) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !((v.Job == nil && rhs.Job == nil) || (v.Job != nil && rhs.Job != nil && v.Job.Equals(rhs.Job))) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of ReadOnlyScheduler_GetConfigSummary_Args.
func (v *ReadOnlyScheduler_GetConfigSummary_Args) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Job != nil {
		err = multierr.Append(err, enc.AddObject("job", v.Job))
	}
	return err
}

// GetJob returns the value of Job if it is set or its
// zero value if it is unset.
func (v *ReadOnlyScheduler_GetConfigSummary_Args) GetJob() (o *JobKey) {
	if v != nil && v.Job != nil {
		return v.Job
	}

	return
}

// IsSetJob returns true if Job is not nil.
func (v *ReadOnlyScheduler_GetConfigSummary_Args) IsSetJob() bool {
	return v != nil && v.Job != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the arguments.
//
// This will always be "getConfigSummary" for this struct.
func (v *ReadOnlyScheduler_GetConfigSummary_Args) MethodName() string {
	return "getConfigSummary"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Call for this struct.
func (v *ReadOnlyScheduler_GetConfigSummary_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

// ReadOnlyScheduler_GetConfigSummary_Helper provides functions that aid in handling the
// parameters and return values of the ReadOnlyScheduler.getConfigSummary
// function.
var ReadOnlyScheduler_GetConfigSummary_Helper = struct {
	// Args accepts the parameters of getConfigSummary in-order and returns
	// the arguments struct for the function.
	Args func(
		job *JobKey,
	) *ReadOnlyScheduler_GetConfigSummary_Args

	// IsException returns true if the given error can be thrown
	// by getConfigSummary.
	//
	// An error can be thrown by getConfigSummary only if the
	// corresponding exception type was mentioned in the 'throws'
	// section for it in the Thrift file.
	IsException func(error) bool

	// WrapResponse returns the result struct for getConfigSummary
	// given its return value and error.
	//
	// This allows mapping values and errors returned by
	// getConfigSummary into a serializable result struct.
	// WrapResponse returns a non-nil error if the provided
	// error cannot be thrown by getConfigSummary
	//
	//   value, err := getConfigSummary(args)
	//   result, err := ReadOnlyScheduler_GetConfigSummary_Helper.WrapResponse(value, err)
	//   if err != nil {
	//     return fmt.Errorf("unexpected error from getConfigSummary: %v", err)
	//   }
	//   serialize(result)
	WrapResponse func(*Response, error) (*ReadOnlyScheduler_GetConfigSummary_Result, error)

	// UnwrapResponse takes the result struct for getConfigSummary
	// and returns the value or error returned by it.
	//
	// The error is non-nil only if getConfigSummary threw an
	// exception.
	//
	//   result := deserialize(bytes)
	//   value, err := ReadOnlyScheduler_GetConfigSummary_Helper.UnwrapResponse(result)
	UnwrapResponse func(*ReadOnlyScheduler_GetConfigSummary_Result) (*Response, error)
}{}

func init() {
	ReadOnlyScheduler_GetConfigSummary_Helper.Args = func(
		job *JobKey,
	) *ReadOnlyScheduler_GetConfigSummary_Args {
		return &ReadOnlyScheduler_GetConfigSummary_Args{
			Job: job,
		}
	}

	ReadOnlyScheduler_GetConfigSummary_Helper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}

	ReadOnlyScheduler_GetConfigSummary_Helper.WrapResponse = func(success *Response, err error) (*ReadOnlyScheduler_GetConfigSummary_Result, error) {
		if err == nil {
			return &ReadOnlyScheduler_GetConfigSummary_Result{Success: success}, nil
		}

		return nil, err
	}
	ReadOnlyScheduler_GetConfigSummary_Helper.UnwrapResponse = func(result *ReadOnlyScheduler_GetConfigSummary_Result) (success *Response, err error) {

		if result.Success != nil {
			success = result.Success
			return
		}

		err = errors.New("expected a non-void result")
		return
	}

}

// ReadOnlyScheduler_GetConfigSummary_Result represents the result of a ReadOnlyScheduler.getConfigSummary function call.
//
// The result of a getConfigSummary execution is sent and received over the wire as this struct.
//
// Success is set only if the function did not throw an exception.
type ReadOnlyScheduler_GetConfigSummary_Result struct {
	// Value returned by getConfigSummary after a successful execution.
	Success *Response `json:"success,omitempty"`
}

// ToWire translates a ReadOnlyScheduler_GetConfigSummary_Result struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ReadOnlyScheduler_GetConfigSummary_Result) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}

	if i != 1 {
		return wire.Value{}, fmt.Errorf("ReadOnlyScheduler_GetConfigSummary_Result should have exactly one field: got %v fields", i)
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a ReadOnlyScheduler_GetConfigSummary_Result struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ReadOnlyScheduler_GetConfigSummary_Result struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ReadOnlyScheduler_GetConfigSummary_Result
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ReadOnlyScheduler_GetConfigSummary_Result) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _Response_Read(field.Value)
				if err != nil {
					return err
				}

			}
		}
	}

	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("ReadOnlyScheduler_GetConfigSummary_Result should have exactly one field: got %v fields", count)
	}

	return nil
}

// String returns a readable string representation of a ReadOnlyScheduler_GetConfigSummary_Result
// struct.
func (v *ReadOnlyScheduler_GetConfigSummary_Result) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}

	return fmt.Sprintf("ReadOnlyScheduler_GetConfigSummary_Result{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this ReadOnlyScheduler_GetConfigSummary_Result match the
// provided ReadOnlyScheduler_GetConfigSummary_Result.
//
// This function performs a deep comparison.
func (v *ReadOnlyScheduler_GetConfigSummary_Result) Equals(rhs *ReadOnlyScheduler_GetConfigSummary_Result) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !((v.Success == nil && rhs.Success == nil) || (v.Success != nil && rhs.Success != nil && v.Success.Equals(rhs.Success))) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of ReadOnlyScheduler_GetConfigSummary_Result.
func (v *ReadOnlyScheduler_GetConfigSummary_Result) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Success != nil {
		err = multierr.Append(err, enc.AddObject("success", v.Success))
	}
	return err
}

// GetSuccess returns the value of Success if it is set or its
// zero value if it is unset.
func (v *ReadOnlyScheduler_GetConfigSummary_Result) GetSuccess() (o *Response) {
	if v != nil && v.Success != nil {
		return v.Success
	}

	return
}

// IsSetSuccess returns true if Success is not nil.
func (v *ReadOnlyScheduler_GetConfigSummary_Result) IsSetSuccess() bool {
	return v != nil && v.Success != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the result.
//
// This will always be "getConfigSummary" for this struct.
func (v *ReadOnlyScheduler_GetConfigSummary_Result) MethodName() string {
	return "getConfigSummary"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Reply for this struct.
func (v *ReadOnlyScheduler_GetConfigSummary_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
