// Code generated by thriftrw v1.19.1. DO NOT EDIT.
// @generated

package api

import (
	errors "errors"
	fmt "fmt"
	multierr "go.uber.org/multierr"
	wire "go.uber.org/thriftrw/wire"
	zapcore "go.uber.org/zap/zapcore"
	strings "strings"
)

// ReadOnlyScheduler_GetJobSummary_Args represents the arguments for the ReadOnlyScheduler.getJobSummary function.
//
// The arguments for getJobSummary are sent and received over the wire as this struct.
type ReadOnlyScheduler_GetJobSummary_Args struct {
	Role *string `json:"role,omitempty"`
}

// ToWire translates a ReadOnlyScheduler_GetJobSummary_Args struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ReadOnlyScheduler_GetJobSummary_Args) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Role != nil {
		w, err = wire.NewValueString(*(v.Role)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a ReadOnlyScheduler_GetJobSummary_Args struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ReadOnlyScheduler_GetJobSummary_Args struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ReadOnlyScheduler_GetJobSummary_Args
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ReadOnlyScheduler_GetJobSummary_Args) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.Role = &x
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a ReadOnlyScheduler_GetJobSummary_Args
// struct.
func (v *ReadOnlyScheduler_GetJobSummary_Args) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [1]string
	i := 0
	if v.Role != nil {
		fields[i] = fmt.Sprintf("Role: %v", *(v.Role))
		i++
	}

	return fmt.Sprintf("ReadOnlyScheduler_GetJobSummary_Args{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this ReadOnlyScheduler_GetJobSummary_Args match the
// provided ReadOnlyScheduler_GetJobSummary_Args.
//
// This function performs a deep comparison.
func (v *ReadOnlyScheduler_GetJobSummary_Args) Equals(rhs *ReadOnlyScheduler_GetJobSummary_Args) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !_String_EqualsPtr(v.Role, rhs.Role) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of ReadOnlyScheduler_GetJobSummary_Args.
func (v *ReadOnlyScheduler_GetJobSummary_Args) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Role != nil {
		enc.AddString("role", *v.Role)
	}
	return err
}

// GetRole returns the value of Role if it is set or its
// zero value if it is unset.
func (v *ReadOnlyScheduler_GetJobSummary_Args) GetRole() (o string) {
	if v != nil && v.Role != nil {
		return *v.Role
	}

	return
}

// IsSetRole returns true if Role is not nil.
func (v *ReadOnlyScheduler_GetJobSummary_Args) IsSetRole() bool {
	return v != nil && v.Role != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the arguments.
//
// This will always be "getJobSummary" for this struct.
func (v *ReadOnlyScheduler_GetJobSummary_Args) MethodName() string {
	return "getJobSummary"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Call for this struct.
func (v *ReadOnlyScheduler_GetJobSummary_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

// ReadOnlyScheduler_GetJobSummary_Helper provides functions that aid in handling the
// parameters and return values of the ReadOnlyScheduler.getJobSummary
// function.
var ReadOnlyScheduler_GetJobSummary_Helper = struct {
	// Args accepts the parameters of getJobSummary in-order and returns
	// the arguments struct for the function.
	Args func(
		role *string,
	) *ReadOnlyScheduler_GetJobSummary_Args

	// IsException returns true if the given error can be thrown
	// by getJobSummary.
	//
	// An error can be thrown by getJobSummary only if the
	// corresponding exception type was mentioned in the 'throws'
	// section for it in the Thrift file.
	IsException func(error) bool

	// WrapResponse returns the result struct for getJobSummary
	// given its return value and error.
	//
	// This allows mapping values and errors returned by
	// getJobSummary into a serializable result struct.
	// WrapResponse returns a non-nil error if the provided
	// error cannot be thrown by getJobSummary
	//
	//   value, err := getJobSummary(args)
	//   result, err := ReadOnlyScheduler_GetJobSummary_Helper.WrapResponse(value, err)
	//   if err != nil {
	//     return fmt.Errorf("unexpected error from getJobSummary: %v", err)
	//   }
	//   serialize(result)
	WrapResponse func(*Response, error) (*ReadOnlyScheduler_GetJobSummary_Result, error)

	// UnwrapResponse takes the result struct for getJobSummary
	// and returns the value or error returned by it.
	//
	// The error is non-nil only if getJobSummary threw an
	// exception.
	//
	//   result := deserialize(bytes)
	//   value, err := ReadOnlyScheduler_GetJobSummary_Helper.UnwrapResponse(result)
	UnwrapResponse func(*ReadOnlyScheduler_GetJobSummary_Result) (*Response, error)
}{}

func init() {
	ReadOnlyScheduler_GetJobSummary_Helper.Args = func(
		role *string,
	) *ReadOnlyScheduler_GetJobSummary_Args {
		return &ReadOnlyScheduler_GetJobSummary_Args{
			Role: role,
		}
	}

	ReadOnlyScheduler_GetJobSummary_Helper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}

	ReadOnlyScheduler_GetJobSummary_Helper.WrapResponse = func(success *Response, err error) (*ReadOnlyScheduler_GetJobSummary_Result, error) {
		if err == nil {
			return &ReadOnlyScheduler_GetJobSummary_Result{Success: success}, nil
		}

		return nil, err
	}
	ReadOnlyScheduler_GetJobSummary_Helper.UnwrapResponse = func(result *ReadOnlyScheduler_GetJobSummary_Result) (success *Response, err error) {

		if result.Success != nil {
			success = result.Success
			return
		}

		err = errors.New("expected a non-void result")
		return
	}

}

// ReadOnlyScheduler_GetJobSummary_Result represents the result of a ReadOnlyScheduler.getJobSummary function call.
//
// The result of a getJobSummary execution is sent and received over the wire as this struct.
//
// Success is set only if the function did not throw an exception.
type ReadOnlyScheduler_GetJobSummary_Result struct {
	// Value returned by getJobSummary after a successful execution.
	Success *Response `json:"success,omitempty"`
}

// ToWire translates a ReadOnlyScheduler_GetJobSummary_Result struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ReadOnlyScheduler_GetJobSummary_Result) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}

	if i != 1 {
		return wire.Value{}, fmt.Errorf("ReadOnlyScheduler_GetJobSummary_Result should have exactly one field: got %v fields", i)
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a ReadOnlyScheduler_GetJobSummary_Result struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ReadOnlyScheduler_GetJobSummary_Result struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ReadOnlyScheduler_GetJobSummary_Result
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ReadOnlyScheduler_GetJobSummary_Result) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _Response_Read(field.Value)
				if err != nil {
					return err
				}

			}
		}
	}

	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("ReadOnlyScheduler_GetJobSummary_Result should have exactly one field: got %v fields", count)
	}

	return nil
}

// String returns a readable string representation of a ReadOnlyScheduler_GetJobSummary_Result
// struct.
func (v *ReadOnlyScheduler_GetJobSummary_Result) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}

	return fmt.Sprintf("ReadOnlyScheduler_GetJobSummary_Result{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this ReadOnlyScheduler_GetJobSummary_Result match the
// provided ReadOnlyScheduler_GetJobSummary_Result.
//
// This function performs a deep comparison.
func (v *ReadOnlyScheduler_GetJobSummary_Result) Equals(rhs *ReadOnlyScheduler_GetJobSummary_Result) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !((v.Success == nil && rhs.Success == nil) || (v.Success != nil && rhs.Success != nil && v.Success.Equals(rhs.Success))) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of ReadOnlyScheduler_GetJobSummary_Result.
func (v *ReadOnlyScheduler_GetJobSummary_Result) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Success != nil {
		err = multierr.Append(err, enc.AddObject("success", v.Success))
	}
	return err
}

// GetSuccess returns the value of Success if it is set or its
// zero value if it is unset.
func (v *ReadOnlyScheduler_GetJobSummary_Result) GetSuccess() (o *Response) {
	if v != nil && v.Success != nil {
		return v.Success
	}

	return
}

// IsSetSuccess returns true if Success is not nil.
func (v *ReadOnlyScheduler_GetJobSummary_Result) IsSetSuccess() bool {
	return v != nil && v.Success != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the result.
//
// This will always be "getJobSummary" for this struct.
func (v *ReadOnlyScheduler_GetJobSummary_Result) MethodName() string {
	return "getJobSummary"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Reply for this struct.
func (v *ReadOnlyScheduler_GetJobSummary_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
