// Code generated by thriftrw v1.19.1. DO NOT EDIT.
// @generated

package api

import (
	errors "errors"
	fmt "fmt"
	multierr "go.uber.org/multierr"
	wire "go.uber.org/thriftrw/wire"
	zapcore "go.uber.org/zap/zapcore"
	strings "strings"
)

// ReadOnlyScheduler_PopulateJobConfig_Args represents the arguments for the ReadOnlyScheduler.populateJobConfig function.
//
// The arguments for populateJobConfig are sent and received over the wire as this struct.
type ReadOnlyScheduler_PopulateJobConfig_Args struct {
	Description *JobConfiguration `json:"description,omitempty"`
}

// ToWire translates a ReadOnlyScheduler_PopulateJobConfig_Args struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ReadOnlyScheduler_PopulateJobConfig_Args) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Description != nil {
		w, err = v.Description.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a ReadOnlyScheduler_PopulateJobConfig_Args struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ReadOnlyScheduler_PopulateJobConfig_Args struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ReadOnlyScheduler_PopulateJobConfig_Args
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ReadOnlyScheduler_PopulateJobConfig_Args) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.Description, err = _JobConfiguration_Read(field.Value)
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a ReadOnlyScheduler_PopulateJobConfig_Args
// struct.
func (v *ReadOnlyScheduler_PopulateJobConfig_Args) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [1]string
	i := 0
	if v.Description != nil {
		fields[i] = fmt.Sprintf("Description: %v", v.Description)
		i++
	}

	return fmt.Sprintf("ReadOnlyScheduler_PopulateJobConfig_Args{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this ReadOnlyScheduler_PopulateJobConfig_Args match the
// provided ReadOnlyScheduler_PopulateJobConfig_Args.
//
// This function performs a deep comparison.
func (v *ReadOnlyScheduler_PopulateJobConfig_Args) Equals(rhs *ReadOnlyScheduler_PopulateJobConfig_Args) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !((v.Description == nil && rhs.Description == nil) || (v.Description != nil && rhs.Description != nil && v.Description.Equals(rhs.Description))) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of ReadOnlyScheduler_PopulateJobConfig_Args.
func (v *ReadOnlyScheduler_PopulateJobConfig_Args) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Description != nil {
		err = multierr.Append(err, enc.AddObject("description", v.Description))
	}
	return err
}

// GetDescription returns the value of Description if it is set or its
// zero value if it is unset.
func (v *ReadOnlyScheduler_PopulateJobConfig_Args) GetDescription() (o *JobConfiguration) {
	if v != nil && v.Description != nil {
		return v.Description
	}

	return
}

// IsSetDescription returns true if Description is not nil.
func (v *ReadOnlyScheduler_PopulateJobConfig_Args) IsSetDescription() bool {
	return v != nil && v.Description != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the arguments.
//
// This will always be "populateJobConfig" for this struct.
func (v *ReadOnlyScheduler_PopulateJobConfig_Args) MethodName() string {
	return "populateJobConfig"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Call for this struct.
func (v *ReadOnlyScheduler_PopulateJobConfig_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

// ReadOnlyScheduler_PopulateJobConfig_Helper provides functions that aid in handling the
// parameters and return values of the ReadOnlyScheduler.populateJobConfig
// function.
var ReadOnlyScheduler_PopulateJobConfig_Helper = struct {
	// Args accepts the parameters of populateJobConfig in-order and returns
	// the arguments struct for the function.
	Args func(
		description *JobConfiguration,
	) *ReadOnlyScheduler_PopulateJobConfig_Args

	// IsException returns true if the given error can be thrown
	// by populateJobConfig.
	//
	// An error can be thrown by populateJobConfig only if the
	// corresponding exception type was mentioned in the 'throws'
	// section for it in the Thrift file.
	IsException func(error) bool

	// WrapResponse returns the result struct for populateJobConfig
	// given its return value and error.
	//
	// This allows mapping values and errors returned by
	// populateJobConfig into a serializable result struct.
	// WrapResponse returns a non-nil error if the provided
	// error cannot be thrown by populateJobConfig
	//
	//   value, err := populateJobConfig(args)
	//   result, err := ReadOnlyScheduler_PopulateJobConfig_Helper.WrapResponse(value, err)
	//   if err != nil {
	//     return fmt.Errorf("unexpected error from populateJobConfig: %v", err)
	//   }
	//   serialize(result)
	WrapResponse func(*Response, error) (*ReadOnlyScheduler_PopulateJobConfig_Result, error)

	// UnwrapResponse takes the result struct for populateJobConfig
	// and returns the value or error returned by it.
	//
	// The error is non-nil only if populateJobConfig threw an
	// exception.
	//
	//   result := deserialize(bytes)
	//   value, err := ReadOnlyScheduler_PopulateJobConfig_Helper.UnwrapResponse(result)
	UnwrapResponse func(*ReadOnlyScheduler_PopulateJobConfig_Result) (*Response, error)
}{}

func init() {
	ReadOnlyScheduler_PopulateJobConfig_Helper.Args = func(
		description *JobConfiguration,
	) *ReadOnlyScheduler_PopulateJobConfig_Args {
		return &ReadOnlyScheduler_PopulateJobConfig_Args{
			Description: description,
		}
	}

	ReadOnlyScheduler_PopulateJobConfig_Helper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}

	ReadOnlyScheduler_PopulateJobConfig_Helper.WrapResponse = func(success *Response, err error) (*ReadOnlyScheduler_PopulateJobConfig_Result, error) {
		if err == nil {
			return &ReadOnlyScheduler_PopulateJobConfig_Result{Success: success}, nil
		}

		return nil, err
	}
	ReadOnlyScheduler_PopulateJobConfig_Helper.UnwrapResponse = func(result *ReadOnlyScheduler_PopulateJobConfig_Result) (success *Response, err error) {

		if result.Success != nil {
			success = result.Success
			return
		}

		err = errors.New("expected a non-void result")
		return
	}

}

// ReadOnlyScheduler_PopulateJobConfig_Result represents the result of a ReadOnlyScheduler.populateJobConfig function call.
//
// The result of a populateJobConfig execution is sent and received over the wire as this struct.
//
// Success is set only if the function did not throw an exception.
type ReadOnlyScheduler_PopulateJobConfig_Result struct {
	// Value returned by populateJobConfig after a successful execution.
	Success *Response `json:"success,omitempty"`
}

// ToWire translates a ReadOnlyScheduler_PopulateJobConfig_Result struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ReadOnlyScheduler_PopulateJobConfig_Result) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}

	if i != 1 {
		return wire.Value{}, fmt.Errorf("ReadOnlyScheduler_PopulateJobConfig_Result should have exactly one field: got %v fields", i)
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a ReadOnlyScheduler_PopulateJobConfig_Result struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ReadOnlyScheduler_PopulateJobConfig_Result struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ReadOnlyScheduler_PopulateJobConfig_Result
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ReadOnlyScheduler_PopulateJobConfig_Result) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _Response_Read(field.Value)
				if err != nil {
					return err
				}

			}
		}
	}

	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("ReadOnlyScheduler_PopulateJobConfig_Result should have exactly one field: got %v fields", count)
	}

	return nil
}

// String returns a readable string representation of a ReadOnlyScheduler_PopulateJobConfig_Result
// struct.
func (v *ReadOnlyScheduler_PopulateJobConfig_Result) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}

	return fmt.Sprintf("ReadOnlyScheduler_PopulateJobConfig_Result{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this ReadOnlyScheduler_PopulateJobConfig_Result match the
// provided ReadOnlyScheduler_PopulateJobConfig_Result.
//
// This function performs a deep comparison.
func (v *ReadOnlyScheduler_PopulateJobConfig_Result) Equals(rhs *ReadOnlyScheduler_PopulateJobConfig_Result) bool {
	if v == nil {
		return rhs == nil
	} else if rhs == nil {
		return false
	}
	if !((v.Success == nil && rhs.Success == nil) || (v.Success != nil && rhs.Success != nil && v.Success.Equals(rhs.Success))) {
		return false
	}

	return true
}

// MarshalLogObject implements zapcore.ObjectMarshaler, enabling
// fast logging of ReadOnlyScheduler_PopulateJobConfig_Result.
func (v *ReadOnlyScheduler_PopulateJobConfig_Result) MarshalLogObject(enc zapcore.ObjectEncoder) (err error) {
	if v == nil {
		return nil
	}
	if v.Success != nil {
		err = multierr.Append(err, enc.AddObject("success", v.Success))
	}
	return err
}

// GetSuccess returns the value of Success if it is set or its
// zero value if it is unset.
func (v *ReadOnlyScheduler_PopulateJobConfig_Result) GetSuccess() (o *Response) {
	if v != nil && v.Success != nil {
		return v.Success
	}

	return
}

// IsSetSuccess returns true if Success is not nil.
func (v *ReadOnlyScheduler_PopulateJobConfig_Result) IsSetSuccess() bool {
	return v != nil && v.Success != nil
}

// MethodName returns the name of the Thrift function as specified in
// the IDL, for which this struct represent the result.
//
// This will always be "populateJobConfig" for this struct.
func (v *ReadOnlyScheduler_PopulateJobConfig_Result) MethodName() string {
	return "populateJobConfig"
}

// EnvelopeType returns the kind of value inside this struct.
//
// This will always be Reply for this struct.
func (v *ReadOnlyScheduler_PopulateJobConfig_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
