// Code generated by thriftrw-plugin-yarpc
// @generated

package auroraschedulermanagerfx

import (
	auroraschedulermanagerserver "github.com/uber/peloton/.gen/thrift/aurora/api/auroraschedulermanagerserver"
	fx "go.uber.org/fx"
	transport "go.uber.org/yarpc/api/transport"
	thrift "go.uber.org/yarpc/encoding/thrift"
)

// ServerParams defines the dependencies for the AuroraSchedulerManager server.
type ServerParams struct {
	fx.In

	Handler auroraschedulermanagerserver.Interface
}

// ServerResult defines the output of AuroraSchedulerManager server module. It provides the
// procedures of a AuroraSchedulerManager handler to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group. Dig 1.2 or newer
// must be used for this feature to work.
type ServerResult struct {
	fx.Out

	Procedures []transport.Procedure `group:"yarpcfx"`
}

// Server provides procedures for AuroraSchedulerManager to an Fx application. It expects a
// auroraschedulermanagerfx.Interface to be present in the container.
//
// 	fx.Provide(
// 		func(h *MyAuroraSchedulerManagerHandler) auroraschedulermanagerserver.Interface {
// 			return h
// 		},
// 		auroraschedulermanagerfx.Server(),
// 	)
func Server(opts ...thrift.RegisterOption) interface{} {
	return func(p ServerParams) ServerResult {
		procedures := auroraschedulermanagerserver.New(p.Handler, opts...)
		return ServerResult{Procedures: procedures}
	}
}
