// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mesos/v1/allocator/allocator.proto

package mesos_v1_allocator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "github.com/uber/peloton/.gen/mesos/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InverseOfferStatus_Status int32

const (
	// We have not received a response yet. This is the default state before
	// receiving a response.
	InverseOfferStatus_UNKNOWN InverseOfferStatus_Status = 1
	// The framework is ok with the inverse offer. This means it will not
	// violate any SLAs and will attempt to evacuate any tasks running on the
	// agent. If the tasks are not evacuated by the framework, the operator can
	// manually shut down the slave knowing that the framework will not have
	// violated its SLAs.
	InverseOfferStatus_ACCEPT InverseOfferStatus_Status = 2
	// The framework wants to block the maintenance operation from happening. An
	// example would be that it cannot meet its SLA by losing resources.
	InverseOfferStatus_DECLINE InverseOfferStatus_Status = 3
)

var InverseOfferStatus_Status_name = map[int32]string{
	1: "UNKNOWN",
	2: "ACCEPT",
	3: "DECLINE",
}

var InverseOfferStatus_Status_value = map[string]int32{
	"UNKNOWN": 1,
	"ACCEPT":  2,
	"DECLINE": 3,
}

func (x InverseOfferStatus_Status) Enum() *InverseOfferStatus_Status {
	p := new(InverseOfferStatus_Status)
	*p = x
	return p
}

func (x InverseOfferStatus_Status) String() string {
	return proto.EnumName(InverseOfferStatus_Status_name, int32(x))
}

func (x *InverseOfferStatus_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InverseOfferStatus_Status_value, data, "InverseOfferStatus_Status")
	if err != nil {
		return err
	}
	*x = InverseOfferStatus_Status(value)
	return nil
}

func (InverseOfferStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_55f9a0bc68075089, []int{0, 0}
}

//*
// Describes the status of an inverse offer.
//
// This is a protobuf so as to be able to share the status to inverse offers
// through endpoints such as the maintenance status endpoint.
type InverseOfferStatus struct {
	Status      *InverseOfferStatus_Status `protobuf:"varint,1,req,name=status,enum=mesos.v1.allocator.InverseOfferStatus_Status" json:"status,omitempty"`
	FrameworkId *v1.FrameworkID            `protobuf:"bytes,2,req,name=framework_id,json=frameworkId" json:"framework_id,omitempty"`
	// Time, since the epoch, when this status was last updated.
	Timestamp            *v1.TimeInfo `protobuf:"bytes,3,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InverseOfferStatus) Reset()         { *m = InverseOfferStatus{} }
func (m *InverseOfferStatus) String() string { return proto.CompactTextString(m) }
func (*InverseOfferStatus) ProtoMessage()    {}
func (*InverseOfferStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f9a0bc68075089, []int{0}
}

func (m *InverseOfferStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InverseOfferStatus.Unmarshal(m, b)
}
func (m *InverseOfferStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InverseOfferStatus.Marshal(b, m, deterministic)
}
func (m *InverseOfferStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InverseOfferStatus.Merge(m, src)
}
func (m *InverseOfferStatus) XXX_Size() int {
	return xxx_messageInfo_InverseOfferStatus.Size(m)
}
func (m *InverseOfferStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InverseOfferStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InverseOfferStatus proto.InternalMessageInfo

func (m *InverseOfferStatus) GetStatus() InverseOfferStatus_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return InverseOfferStatus_UNKNOWN
}

func (m *InverseOfferStatus) GetFrameworkId() *v1.FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *InverseOfferStatus) GetTimestamp() *v1.TimeInfo {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterEnum("mesos.v1.allocator.InverseOfferStatus_Status", InverseOfferStatus_Status_name, InverseOfferStatus_Status_value)
	proto.RegisterType((*InverseOfferStatus)(nil), "mesos.v1.allocator.InverseOfferStatus")
}

func init() { proto.RegisterFile("mesos/v1/allocator/allocator.proto", fileDescriptor_55f9a0bc68075089) }

var fileDescriptor_55f9a0bc68075089 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0x69, 0x07, 0x15, 0x5f, 0x45, 0x4a, 0x50, 0x28, 0x82, 0x30, 0x7a, 0x71, 0x17, 0x33,
	0xb7, 0x93, 0x57, 0xd7, 0x55, 0x08, 0x4a, 0x37, 0xea, 0xc4, 0xa3, 0x84, 0xed, 0x55, 0x8b, 0xcb,
	0x5e, 0x49, 0x62, 0xfd, 0xe9, 0x5e, 0x65, 0xdd, 0x6c, 0x0e, 0xdb, 0x29, 0x0f, 0xbe, 0xef, 0x7b,
	0x24, 0x81, 0x44, 0xa1, 0x21, 0x33, 0x6c, 0x46, 0x43, 0xb9, 0x5e, 0xd3, 0x52, 0x5a, 0xd2, 0x6e,
	0xe2, 0xb5, 0x26, 0x4b, 0x8c, 0xb5, 0x0e, 0x6f, 0x46, 0xbc, 0x23, 0x57, 0x17, 0x5d, 0xb7, 0x83,
	0xad, 0x99, 0xfc, 0x7a, 0xc0, 0xc4, 0xa6, 0x41, 0x6d, 0x70, 0x56, 0x96, 0xa8, 0x5f, 0xac, 0xb4,
	0xdf, 0x86, 0x65, 0x10, 0x98, 0x76, 0x8a, 0xbd, 0xbe, 0x3f, 0x38, 0x1f, 0xdf, 0xf2, 0xc3, 0x8d,
	0xfc, 0xb0, 0xe3, 0xbb, 0xa3, 0xd8, 0xc7, 0xec, 0x1e, 0xce, 0x4a, 0x2d, 0x15, 0xfe, 0x90, 0xfe,
	0x7a, 0xaf, 0x56, 0xb1, 0xdf, 0xf7, 0x07, 0xe1, 0xf8, 0xd2, 0x2d, 0x7b, 0xfc, 0xa7, 0x62, 0x5a,
	0x84, 0x9d, 0x2a, 0x56, 0xec, 0x0e, 0x4e, 0x6d, 0xa5, 0xd0, 0x58, 0xa9, 0xea, 0xb8, 0xd7, 0x66,
	0xcc, 0x65, 0x8b, 0x4a, 0xa1, 0xd8, 0x94, 0x54, 0x38, 0x29, 0xe1, 0x10, 0xec, 0x2f, 0x1f, 0xc2,
	0xc9, 0x6b, 0xfe, 0x94, 0xcf, 0xde, 0xf2, 0xc8, 0x63, 0x00, 0xc1, 0x43, 0x9a, 0x66, 0xf3, 0x45,
	0xe4, 0x6f, 0xc1, 0x34, 0x4b, 0x9f, 0x45, 0x9e, 0x45, 0xbd, 0xc9, 0x0d, 0x5c, 0x93, 0xfe, 0xe0,
	0xb2, 0x96, 0xcb, 0x4f, 0x3c, 0xf2, 0xbc, 0x49, 0x30, 0xdf, 0xfe, 0x90, 0xf9, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0xe9, 0x0a, 0x4a, 0x2e, 0x71, 0x01, 0x00, 0x00,
}
