#!/bin/bash

set -e

aurora_tree=/tmp/aurora
aurora_dir=tools/deploy/aurora

mkdir -p tmp

# Check out Uber apache-aurora repo
rm -rf ${aurora_tree}

git clone github.com/apache/aurora.git ${aurora_tree}

cp ${aurora_tree}/src/main/python/apache/aurora/config/schema/base.py \
    ${aurora_dir}/schema/aurora/base.py

cp ${aurora_tree}/src/main/python/apache/thermos/config/schema.py \
    ${aurora_dir}/schema/thermos/schema.py

cp ${aurora_tree}/src/main/python/apache/thermos/config/schema_base.py \
    ${aurora_dir}/schema/thermos/schema_base.py

# Copy and update python namespace in api.thrift
sed "s/^namespace py gen.apache.aurora.api/namespace py aurora.api/" \
    ${aurora_tree}/api/src/main/thrift/org/apache/aurora/gen/api.thrift > \
    ${aurora_dir}/api.thrift

# Generate the python types from api.thrift
thrift --gen py:new_style,slots,utf8strings --out tools/deploy/ ${aurora_dir}/api.thrift

# The __hash__ function generated by thrift 0.9.3 is incompabitable
# with thrift 0.9.2post6 python package so we have to delete __hash__ functions
sed '/^  def __hash__(self):/,/^    return value/d' \
    ${aurora_dir}/api/ttypes.py > ${aurora_dir}/api/ttypes.py.new
mv ${aurora_dir}/api/ttypes.py.new ${aurora_dir}/api/ttypes.py
