// Code generated by thriftrw-plugin-yarpc
// @generated

package readonlyschedulerfx

import (
	readonlyschedulerserver "github.com/uber/peloton/.gen/thrift/aurora/api/readonlyschedulerserver"
	fx "go.uber.org/fx"
	transport "go.uber.org/yarpc/api/transport"
	thrift "go.uber.org/yarpc/encoding/thrift"
)

// ServerParams defines the dependencies for the ReadOnlyScheduler server.
type ServerParams struct {
	fx.In

	Handler readonlyschedulerserver.Interface
}

// ServerResult defines the output of ReadOnlyScheduler server module. It provides the
// procedures of a ReadOnlyScheduler handler to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group. Dig 1.2 or newer
// must be used for this feature to work.
type ServerResult struct {
	fx.Out

	Procedures []transport.Procedure `group:"yarpcfx"`
}

// Server provides procedures for ReadOnlyScheduler to an Fx application. It expects a
// readonlyschedulerfx.Interface to be present in the container.
//
// 	fx.Provide(
// 		func(h *MyReadOnlySchedulerHandler) readonlyschedulerserver.Interface {
// 			return h
// 		},
// 		readonlyschedulerfx.Server(),
// 	)
func Server(opts ...thrift.RegisterOption) interface{} {
	return func(p ServerParams) ServerResult {
		procedures := readonlyschedulerserver.New(p.Handler, opts...)
		return ServerResult{Procedures: procedures}
	}
}
