// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package api

import (
	"bytes"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

const AURORA_EXECUTOR_NAME = "AuroraExecutor"

var ACTIVE_STATES map[ScheduleStatus]struct{}
var SLAVE_ASSIGNED_STATES map[ScheduleStatus]struct{}
var LIVE_STATES map[ScheduleStatus]struct{}
var TERMINAL_STATES map[ScheduleStatus]struct{}

const GOOD_IDENTIFIER_PATTERN = "^[\\w\\-\\.]+$"
const GOOD_IDENTIFIER_PATTERN_JVM = "^[\\w\\-\\.]+$"
const GOOD_IDENTIFIER_PATTERN_PYTHON = "^[\\w\\-\\.]+$"

var ACTIVE_JOB_UPDATE_STATES map[JobUpdateStatus]struct{}
var AWAITNG_PULSE_JOB_UPDATE_STATES map[JobUpdateStatus]struct{}

const BYPASS_LEADER_REDIRECT_HEADER_NAME = "Bypass-Leader-Redirect"
const TASK_FILESYSTEM_MOUNT_POINT = "taskfs"

func init() {
	ACTIVE_STATES = map[ScheduleStatus]struct{}{
		9:  {},
		17: {},
		6:  {},
		0:  {},
		13: {},
		12: {},
		2:  {},
		1:  {},
		16: {},
	}

	SLAVE_ASSIGNED_STATES = map[ScheduleStatus]struct{}{
		9:  {},
		17: {},
		6:  {},
		13: {},
		12: {},
		2:  {},
		1:  {},
	}

	LIVE_STATES = map[ScheduleStatus]struct{}{
		6:  {},
		13: {},
		12: {},
		17: {},
		2:  {},
	}

	TERMINAL_STATES = map[ScheduleStatus]struct{}{
		4: {},
		3: {},
		5: {},
		7: {},
	}

	ACTIVE_JOB_UPDATE_STATES = map[JobUpdateStatus]struct{}{
		0:  {},
		1:  {},
		2:  {},
		3:  {},
		9:  {},
		10: {},
	}

	AWAITNG_PULSE_JOB_UPDATE_STATES = map[JobUpdateStatus]struct{}{
		9:  {},
		10: {},
	}

}
