// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peloton/api/v0/changelog/changelog.proto

package changelog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
//  Change log of the entity info
type ChangeLog struct {
	// Version number of the entity info which is monotonically increasing.
	// Clients can use this to guide against race conditions using MVCC.
	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// The timestamp when the entity info is created
	CreatedAt int64 `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// The timestamp when the entity info is updated
	UpdatedAt int64 `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	// The entity of the user that updated the entity info
	UpdatedBy            string   `protobuf:"bytes,4,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeLog) Reset()         { *m = ChangeLog{} }
func (m *ChangeLog) String() string { return proto.CompactTextString(m) }
func (*ChangeLog) ProtoMessage()    {}
func (*ChangeLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_c99db043a704a9e1, []int{0}
}

func (m *ChangeLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeLog.Unmarshal(m, b)
}
func (m *ChangeLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeLog.Marshal(b, m, deterministic)
}
func (m *ChangeLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeLog.Merge(m, src)
}
func (m *ChangeLog) XXX_Size() int {
	return xxx_messageInfo_ChangeLog.Size(m)
}
func (m *ChangeLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeLog.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeLog proto.InternalMessageInfo

func (m *ChangeLog) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ChangeLog) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ChangeLog) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *ChangeLog) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func init() {
	proto.RegisterType((*ChangeLog)(nil), "peloton.api.v0.changelog.ChangeLog")
}

func init() {
	proto.RegisterFile("peloton/api/v0/changelog/changelog.proto", fileDescriptor_c99db043a704a9e1)
}

var fileDescriptor_c99db043a704a9e1 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0x48, 0xcd, 0xc9,
	0x2f, 0xc9, 0xcf, 0xd3, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x33, 0xd0, 0x4f, 0xce, 0x48, 0xcc, 0x4b,
	0x4f, 0xcd, 0xc9, 0x4f, 0x47, 0xb0, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x24, 0xa0, 0x2a,
	0xf5, 0x12, 0x0b, 0x32, 0xf5, 0xca, 0x0c, 0xf4, 0xe0, 0xf2, 0x4a, 0xf5, 0x5c, 0x9c, 0xce, 0x60,
	0x8e, 0x4f, 0x7e, 0xba, 0x90, 0x04, 0x17, 0x7b, 0x59, 0x6a, 0x51, 0x71, 0x66, 0x7e, 0x9e, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x8c, 0x2b, 0x24, 0xc3, 0xc5, 0x99, 0x5c, 0x94, 0x9a, 0x58,
	0x92, 0x9a, 0xe2, 0x58, 0x22, 0xc1, 0x04, 0x96, 0x43, 0x08, 0x80, 0x64, 0x4b, 0x0b, 0x52, 0xa0,
	0xb2, 0xcc, 0x10, 0x59, 0xb8, 0x00, 0x92, 0xac, 0x53, 0xa5, 0x04, 0x8b, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x42, 0xc0, 0xc9, 0x84, 0x0b, 0xa7, 0xe3, 0xa2, 0x24, 0x70, 0x79, 0x30, 0x89, 0x0d, 0xec,
	0x2f, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x23, 0x53, 0xee, 0x36, 0x03, 0x01, 0x00, 0x00,
}
