// Code generated by thriftrw-plugin-yarpc
// @generated

// Package auroraadminfx provides better integration for Fx for services
// implementing or calling AuroraAdmin.
//
// Clients
//
// If you are making requests to AuroraAdmin, use the Client function to inject a
// AuroraAdmin client into your container.
//
// 	fx.Provide(auroraadminfx.Client("..."))
//
// Servers
//
// If you are implementing AuroraAdmin, provide a auroraadminserver.Interface into
// the container and use the Server function.
//
// Given,
//
// 	func NewAuroraAdminHandler() auroraadminserver.Interface
//
// You can do the following to have the procedures of AuroraAdmin made available
// to an Fx application.
//
// 	fx.Provide(
// 		NewAuroraAdminHandler,
// 		auroraadminfx.Server(),
// 	)
package auroraadminfx
